num1=float(input("Ingrese el primer número: "))
num2=float(input("Ingrese el segundo número: "))

print("suma")
print(num1,"+", num2, "=", num1+num2   )
print("resta")
print(num1,"-", num2, "=", num1-num2   )            
print("multiplicación")
print(num1,"*", num2, "=", num1*num2   )
print("división")
print(num1,"/", num2, "=", num1/num2   )
print("módulo")
print(num1,"%", num2, "=", num1%num2   )
print("exponenciación")
print(num1,"**", num2, "=", num1**num2   )
